/**
 * Valeurs par défaut extraites des pages — utilisées dans le backoffice
 * pour pré-remplir les champs quand aucun override n'a été sauvegardé.
 *
 * Généré automatiquement à partir des fichiers app\/*\*\/page.tsx.
 * Ne pas éditer manuellement — relancer l'extraction si les pages changent.
 */
export const PAGE_DEFAULTS: Record<string, Record<string, string>> = {
  'a-propos': {
    meta_title: 'À Propos — Amani Limousines | Service de Chauffeur Privé de Prestige à Paris',
    meta_description: "Amani Limousines, service de chauffeur privé de prestige à Paris. Notre histoire, nos valeurs, notre flotte de 300+ véhicules. Ambassades, palaces, aviation privée.",
    h1: 'Amani Limousines — service de chauffeur privé de prestige à Paris',
    intro: "Amani Limousines est un prestataire de transport de prestige basé à Paris, spécialisé dans le service aux ambassades, aux États étrangers, aux family offices, aux palaces parisiens et à l'aviation privée. Nous opérons 24 heures sur 24, 365 jours par an, avec une flotte de plus de 300 véhicules de moins de trois ans.",
  },
  'chauffeur-anglophone': {
    meta_title: 'Chauffeur Anglophone Paris — Chauffeur Privé Parlant Anglais | Amani Limousines',
    meta_description: "Chauffeur privé parlant anglais à Paris. Transferts aéroports, rendez-vous d'affaires, tourisme de luxe. Communication fluide en anglais. Disponible 24h/24.",
    h1: 'Chauffeur privé anglophone à Paris',
    intro: "Ça change tout d'avoir un chauffeur qui parle votre langue. Plus besoin de montrer l'adresse sur votre téléphone ou de répéter trois fois le nom de l'hôtel. Vous montez, vous expliquez ce dont vous avez besoin, et c'est réglé. On a des chauffeurs qui parlent couramment anglais, dispo jour et nuit, qui connaissent Paris comme leur poche. Que vous soyez là pour le boulot ou en vacances, c'est juste plus simple comme ça.",
  },
  'chauffeur-arabophone': {
    meta_title: 'Chauffeur Arabophone Paris — Chauffeur Privé Parlant Arabe | Amani Limousines',
    meta_description: "Chauffeur privé parlant arabe à Paris. Accueil délégations du Golfe, shopping de luxe, tourisme médical. Communication en arabe. Disponible 24h/24.",
    h1: 'Chauffeur privé arabophone à Paris',
    intro: "On reçoit beaucoup de familles et de voyageurs du monde arabe à Paris. Ce qu'ils nous disent souvent : le plus important, c'est d'avoir quelqu'un qui parle leur langue et qui connaît la ville. Un chauffeur arabophone, ça veut dire zéro galère pour expliquer où vous allez, ce dont vous avez besoin, ou comment organiser la journée. Il connaît les bonnes adresses, il sait comment ça marche à Paris, et il est dispo quand vous en avez besoin.",
  },
  'chauffeur-coreen': {
    meta_title: 'Chauffeur Coréen Paris — Chauffeur Privé Parlant Coréen | Amani Limousines',
    meta_description: "Chauffeur privé parlant coréen à Paris. K-beauty, mode, tourisme, événements corporate. Communication en coréen. Disponible 24h/24.",
    h1: 'Chauffeur privé parlant coréen à Paris',
    intro: "Les Coréens à Paris, on en voit de plus en plus. Acheteurs mode pendant la Fashion Week, touristes passionnés par la culture française, cadres des grands groupes en déplacement pro. Le point commun de tous ces voyageurs : avoir un chauffeur qui parle coréen rend le séjour tellement plus simple. Plus besoin de galérer avec Google Translate pour donner une adresse. Le chauffeur est là, il parle votre langue, il connaît Paris. C'est tout.",
  },
  'chauffeur-diplomatique': {
    meta_title: 'Chauffeur Diplomatique Paris — Transport Officiel & Protocole | Amani Limousines',
    meta_description: "Transport diplomatique à Paris : convois officiels, ambassades, sommets internationaux. Chauffeurs habilités, véhicules blindés, protocole respecté. Discrétion et multilinguisme.",
    h1: 'Chauffeur diplomatique à Paris — protocole, discrétion et sécurité',
    intro: "Le transport diplomatique à Paris obéit à des règles que la plupart des sociétés de VTC ne connaissent pas. Ordre protocolaire des véhicules, itinéraires validés par les services de sécurité, communication chiffrée entre chauffeurs, ponctualité à la seconde — ce sont les standards auxquels nous nous conformons. Amani Limousines travaille avec des ambassades, des organisations internationales et des délégations étrangères en visite à Paris.",
  },
  'chauffeur-evenements-sportifs': {
    meta_title: 'Chauffeur Événements Sportifs — Transport VIP Compétitions | Amani Limousines',
    meta_description: "Chauffeur privé pour événements sportifs : Roland-Garros, Grand Prix Monaco, 24h du Mans, Tour de France, courses hippiques. VIP hospitality, navettes équipes, transferts athlètes.",
    h1: 'Chauffeur pour événements sportifs — transport VIP pour les grandes compétitions',
    intro: "Les grands événements sportifs génèrent une logistique de transport complexe : accès restreints, routes fermées, affluence massive, horaires imprévisibles. Amani Limousines intervient sur les plus grandes compétitions sportives en France et à Monaco, avec des chauffeurs qui connaissent les sites, les protocoles d'accès et les itinéraires de repli. Que vous soyez athlète, sponsor, organisateur ou spectateur VIP, le transport ne doit jamais être un sujet de préoccupation le jour J.",
  },
  'chauffeur-fashion-week': {
    meta_title: 'Chauffeur Fashion Week Paris — Transport VIP Mode & Luxe | Amani Limousines',
    meta_description: "Chauffeur privé pour la Fashion Week de Paris, Milan et Londres. Transport mannequins, designers, acheteurs. Shows, showrooms, afterparties. Flotte Mercedes.",
    h1: 'Chauffeur Fashion Week Paris — transport sur mesure pour le monde de la mode',
    intro: "La Fashion Week de Paris impose un rythme que les transports classiques ne suivent pas. Quatre shows dans la journée, un dîner le soir, un afterparty ensuite — et chaque lieu est à l'autre bout de Paris. Amani Limousines accompagne maisons de couture, acheteurs, mannequins et presse depuis plusieurs saisons. Nos chauffeurs connaissent les lieux, les accès réservés et les horaires réels, pas ceux du programme officiel.",
  },
  'chauffeur-germanophone': {
    meta_title: 'Chauffeur Germanophone Paris — Chauffeur Privé Parlant Allemand | Amani Limousines',
    meta_description: "Chauffeur privé parlant allemand à Paris. Industrie automobile, conventions professionnelles, tourisme. Communication en allemand. Disponible 24h/24.",
    h1: 'Chauffeur privé germanophone à Paris',
    intro: "On va être direct : si vous venez d'Allemagne, d'Autriche ou de Suisse pour bosser à Paris, vous avez besoin d'un chauffeur ponctuel, qui parle allemand, et qui ne perd pas votre temps. C'est exactement ce qu'on propose. Un chauffeur germanophone qui connaît le périph, les gares, les quartiers d'affaires, et qui communique dans votre langue sans approximation. Dispo 24h/24, partout en Île-de-France.",
  },
  'chauffeur-hispanophone': {
    meta_title: 'Chauffeur Hispanophone Paris — Chauffeur Privé Parlant Espagnol | Amani Limousines',
    meta_description: "Chauffeur privé parlant espagnol à Paris. Tourisme, affaires, visites diplomatiques. Communication fluide en español. Disponible 24h/24.",
    h1: 'Chauffeur privé hispanophone à Paris',
    intro: "Il y a énormément de visiteurs hispanophones à Paris — des touristes mexicains, des hommes d'affaires espagnols, des diplomates colombiens, des familles argentines. Le point commun : quand on a un chauffeur qui parle espagnol, tout devient plus facile. Les instructions sont claires, l'ambiance est détendue, et on peut vraiment profiter de la ville au lieu de galérer avec la langue. Nos chauffeurs hispanophones sont là 24h/24.",
  },
  'chauffeur-japonais': {
    meta_title: 'Chauffeur Japonais Paris — Chauffeur Privé Parlant Japonais | Amani Limousines',
    meta_description: "Chauffeur privé parlant japonais à Paris. Haute couture, restaurants étoilés, affaires. Communication en japonais. Disponible 24h/24.",
    h1: 'Chauffeur privé parlant japonais à Paris',
    intro: "Quand un voyageur japonais arrive à Paris, il s'attend à un certain niveau de service. On le sait. C'est pour ça qu'on a des chauffeurs qui parlent japonais et qui connaissent les codes : la ponctualité à la minute, la propreté du véhicule, la discrétion. Pas de blabla inutile, pas de retard, pas d'à-peu-près. Le chauffeur est là quand il faut, où il faut, et il parle votre langue. Dispo 24h/24, tous les jours.",
  },
  'chauffeur-mandarin': {
    meta_title: 'Chauffeur Mandarin Paris — Chauffeur Privé Parlant Chinois | Amani Limousines',
    meta_description: "Chauffeur privé parlant mandarin à Paris. Shopping de luxe, tourisme en groupe, délégations d'affaires chinoises. Communication en chinois. Disponible 24h/24.",
    h1: 'Chauffeur privé parlant mandarin à Paris',
    intro: "Paris attire énormément de visiteurs chinois, et on le voit tous les jours. Le problème, c'est que la barrière de la langue peut vite devenir un vrai casse-tête ici. Avec un chauffeur qui parle mandarin, tout se simplifie. Il connaît les adresses que la clientèle chinoise aime, il sait comment fonctionne Paris, et il parle votre langue. Nos chauffeurs sinophones sont dispo 24h/24, à Paris comme en province.",
  },
  'chauffeur-mariage-paris': {
    meta_title: 'Chauffeur Privé Mariage Paris — Mercedes Classe S et Classe E | Amani Limousines',
    meta_description: "Chauffeur privé pour mariage à Paris et Île-de-France. Mercedes Classe E et Classe S pour les mariés, Sprinter VIP pour les convois. Tarif à la journée ou demi-journée.",
    h1: 'Chauffeur privé pour mariage à Paris — véhicule pour les mariés et les convois',
    intro: "Le transport du mariage, c'est souvent la dernière chose à laquelle on pense et la première à poser problème. Le chauffeur des mariés arrive en retard, le cortège se disperse, quelqu'un doit garder un œil sur les horaires. On s'occupe de tout ça. Flotte Mercedes, disponibilité à la demi-journée ou à la journée, coordination avec votre maître de cérémonie si nécessaire.",
  },
  'chauffeur-mariage': {
    meta_title: 'Chauffeur Mariage France — Voiture avec Chauffeur pour Mariage | Amani Limousines',
    meta_description: "Chauffeur mariage partout en France : Paris, Deauville, Côte d'Azur, châteaux, vignobles. Voiture des mariés, navettes invités, coordination jour J. Mercedes Classe S, Classe G, Maybach.",
    h1: 'Chauffeur mariage en France — de Paris aux vignobles, un transport à la hauteur du jour J',
    intro: "Un mariage ne se déroule pas toujours à Paris. Il a lieu dans un château en Touraine, un mas en Provence, un domaine viticole à Saint-Émilion ou une villa face à la Méditerranée. Amani Limousines assure le transport des mariés et des invités partout en France, avec des véhicules à la mesure de l'événement : Mercedes Classe S, Classe G ou Maybach. Le chauffeur porte le costume, connaît le programme et reste disponible du matin jusqu'au bout de la nuit.",
  },
  'chauffeur-prive-bordeaux': {
    meta_title: 'Chauffeur Privé Bordeaux — Vignobles, Aéroport & Événements | Amani Limousines',
    meta_description: "Chauffeur privé à Bordeaux pour transferts aéroport Mérignac, circuits dans les vignobles de Saint-Émilion et du Médoc, mariages et événements. Flotte Mercedes, tarif fixe.",
    h1: 'Chauffeur privé Bordeaux — vignobles, aéroport et événements',
    intro: "Bordeaux se parcourt en voiture : les châteaux du Médoc sont à quarante minutes du centre, Saint-Émilion à une heure, Arcachon à cinquante minutes. Un chauffeur privé à Bordeaux transforme chaque déplacement en moment de calme. Amani Limousines vous conduit dans toute la Gironde avec des Mercedes récentes, un tarif fixe communiqué avant la réservation et une ponctualité sans négociation.",
  },
  'chauffeur-prive-cannes': {
    meta_title: 'Chauffeur Privé Cannes — Festival, MIPIM & Croisette | Amani Limousines',
    meta_description: "Chauffeur privé à Cannes pour le Festival, le MIPIM, Cannes Lions et vos déplacements sur la Croisette. Mercedes haut de gamme, tarif fixe, service 7j/7.",
    h1: 'Chauffeur privé Cannes — Festival, salons et Croisette',
    intro: "Cannes est une ville compacte mais saturée dès qu'un événement majeur s'y installe. La Croisette devient piétonne, les parkings sont pleins, les VTC classiques débordés. Un chauffeur privé à Cannes connaît les accès alternatifs, les dépose-minutes et les horaires de fermeture des rues. Amani Limousines vous conduit partout à Cannes et dans ses environs, en Mercedes, au tarif fixe convenu avant votre arrivée.",
  },
  'chauffeur-prive-chamonix': {
    meta_title: 'Chauffeur Privé Chamonix — Transfert Paris Chamonix | Amani Limousines',
    meta_description: "Chauffeur privé Paris Chamonix en Mercedes. 600 km, prix fixe sans compteur. Départ CDG, Orly ou Paris intramuros. Disponible 7j/7, toute l'année.",
    h1: 'Chauffeur privé Chamonix — depuis Paris et les aéroports',
    intro: "Paris–Chamonix en voiture avec chauffeur : 600 km de trajet, prix fixe annoncé avant la réservation, aucun supplément. Amani Limousines couvre ce trajet toute l'année, saison de ski comme saison estivale, avec des véhicules Mercedes récents et des chauffeurs habitués aux routes de montagne.",
  },
  'chauffeur-prive-deauville': {
    meta_title: 'Chauffeur Privé Deauville — Hippodrome, Planches & Événements | Amani Limousines',
    meta_description: "Chauffeur privé à Deauville pour les courses hippiques, mariages, Festival du cinéma américain et week-ends sur la côte normande. Mercedes, tarif fixe.",
    h1: 'Chauffeur privé Deauville — courses, festivals et côte normande',
    intro: "Deauville est à deux heures de Paris par l'autoroute, mais la ville n'a ni gare TGV directe ni aéroport commercial. Pour y arriver sereinement, un chauffeur privé depuis Paris est souvent la meilleure option. Amani Limousines assure les transferts Paris–Deauville et les déplacements sur la Côte Fleurie en Mercedes, avec un tarif fixe communiqué à la réservation.",
  },
  'chauffeur-prive-haute-savoie': {
    meta_title: 'Chauffeur Privé Haute-Savoie — Paris vers Chamonix, Megève, Annecy | Amani Limousines',
    meta_description: "Chauffeur privé Paris vers toute la Haute-Savoie : Chamonix, Megève, Annecy, Thonon, Évian. Prix fixe, Mercedes récente. Depuis CDG, Orly ou Paris intramuros.",
    h1: 'Chauffeur privé Haute-Savoie — Chamonix, Megève, Annecy et au-delà',
    intro: "La Haute-Savoie regroupe des destinations que le train dessert mal : Chamonix, Megève, Morzine, la rive française du lac Léman. Amani Limousines couvre l'ensemble du département depuis Paris, CDG et Orly, en Mercedes récentes avec prix fixe. Le trajet fait entre 5h et 7h selon la destination, sans correspondance ni navette locale à coordonner à l'arrivée.",
  },
  'chauffeur-prive-lyon': {
    meta_title: 'Chauffeur Privé Lyon — Aéroport Saint Exupéry & Affaires | Amani Limousines',
    meta_description: "Chauffeur privé à Lyon : transferts aéroport Saint Exupéry, salons Eurexpo, déplacements d'affaires à la Part-Dieu et mise à disposition. Mercedes, tarif fixe.",
    h1: 'Chauffeur privé Lyon — aéroport, affaires et gastronomie',
    intro: "Lyon mêle quartiers d'affaires, patrimoine UNESCO et tables étoilées. Se déplacer entre la Presqu'île, la Part-Dieu et Saint Exupéry demande un chauffeur qui connaît les raccourcis et les horaires de bouchon. Amani Limousines assure vos transferts dans toute l'agglomération lyonnaise avec des véhicules Mercedes, un tarif fixe et une ponctualité rigoureuse.",
  },
  'chauffeur-prive-marseille': {
    meta_title: 'Chauffeur Privé Marseille — Aéroport Provence, Calanques & Affaires | Amani Limousines',
    meta_description: "Chauffeur privé à Marseille : transferts aéroport Marseille-Provence, croisières au Vieux-Port, déplacements vers Aix-en-Provence et les Calanques. Mercedes, tarif fixe.",
    h1: 'Chauffeur privé Marseille — aéroport, croisières et Provence',
    intro: "Marseille est une ville immense qui s'étire sur 57 kilomètres de littoral. De l'aéroport de Marignane au Vieux-Port, de la gare Saint-Charles aux Calanques, les distances sont trompeuses et la circulation imprévisible. Un chauffeur privé à Marseille vous fait gagner du temps et de la sérénité. Amani Limousines couvre Marseille, Aix-en-Provence, Cassis et l'ensemble des Bouches-du-Rhône en Mercedes, au tarif fixe.",
  },
  'chauffeur-prive-megeve': {
    meta_title: 'Chauffeur Privé Megève — Transfert Paris Megève | Amani Limousines',
    meta_description: "Transfert en voiture avec chauffeur Paris–Megève. 640 km, prix fixe. Départ depuis CDG, Orly ou votre adresse. Mercedes récente, disponible 7j/7.",
    h1: 'Chauffeur privé Megève — depuis Paris et les aéroports',
    intro: "Megève est à 640 km de Paris, 6h30 de route avec un chauffeur, et aucune correspondance à gérer. Amani Limousines couvre ce trajet depuis Paris, CDG et Orly en Mercedes récentes, avec prix fixe confirmé avant le départ. L'accès à la station en voiture privée reste la solution la plus directe pour les clients avec des bagages de ski ou plusieurs membres d'un groupe.",
  },
  'chauffeur-prive-monaco': {
    meta_title: 'Chauffeur Privé Monaco — Monte-Carlo, Grand Prix & Yacht Show | Amani Limousines',
    meta_description: "Chauffeur privé à Monaco : Monte-Carlo, Port Hercule, Grand Prix, Yacht Show. Service Mercedes haut de gamme, discrétion garantie, tarif fixe.",
    h1: 'Chauffeur privé Monaco — Monte-Carlo, Grand Prix et prestige',
    intro: "Monaco est un territoire de deux kilomètres carrés où la moindre fermeture de rue paralyse la circulation. Un chauffeur privé à Monaco connaît chaque virage, chaque tunnel et chaque accès réservé de la Principauté. Amani Limousines assure vos déplacements à Monaco et entre Monaco et l'aéroport de Nice en Mercedes, avec un tarif fixe et une discrétion adaptée au standing monégasque.",
  },
  'chauffeur-prive-nice': {
    meta_title: "Chauffeur Privé Nice / Côte d'Azur — Cannes, Monaco, Saint-Tropez | Amani Limousines",
    meta_description: "Chauffeur privé Nice et Côte d'Azur : transferts aéroport Nice, Cannes, Monaco, Saint-Tropez. Service haut de gamme en Mercedes, tarif fixe, disponible 7j/7.",
    h1: "Chauffeur privé Nice — Côte d'Azur, Cannes, Monaco",
    intro: "La Côte d'Azur est un littoral de 120 kilomètres où chaque déplacement dépend de la saison, de l'événement en cours et de l'état de la circulation sur l'autoroute A8. Un chauffeur privé à Nice vous épargne les embouteillages chroniques entre l'aéroport, Cannes et Monaco. Amani Limousines couvre l'ensemble du littoral azuréen avec des Mercedes récentes, un tarif fixe et des chauffeurs qui connaissent chaque raccourci.",
  },
  'chauffeur-prive-paris': {
    meta_title: 'Chauffeur Privé Paris — Service 24h/24, Flotte Mercedes | Amani Limousines',
    meta_description: "Chauffeur privé à Paris pour transferts aéroport, mise à disposition et longue distance. Flotte Mercedes Classe E, S et V. Tarif fixe, ponctualité garantie.",
    h1: 'Chauffeur privé à Paris — disponible 24h/24, sept jours sur sept',
    intro: "Paris est une ville où le temps de trajet peut basculer d'une demi-heure à deux heures selon l'heure et l'itinéraire. Un chauffeur privé à Paris connaît ces variations, les contourne et vous livre à l'heure. Amani Limousines opère dans toute l'Île-de-France depuis 2012 : aéroports, palaces, sièges sociaux, événements. Tarifs fixes, flotte Mercedes, disponibilité sept jours sur sept.",
  },
  'chauffeur-prive-saint-tropez': {
    meta_title: 'Chauffeur Privé Saint-Tropez — Prestige, Yachting & Pampelonne | Amani Limousines',
    meta_description: "Chauffeur privé à Saint-Tropez : transferts depuis Nice ou La Môle, plages de Pampelonne, yachting et soirées privées. Mercedes haut de gamme, tarif fixe.",
    h1: 'Chauffeur privé Saint-Tropez — prestige, plages et soirées',
    intro: "Saint-Tropez est un village de 4 000 habitants qui accueille 80 000 personnes par jour en été. La route départementale qui y mène est à voie unique sur plusieurs kilomètres, et les bouchons du week-end peuvent durer deux heures. Un chauffeur privé à Saint-Tropez connaît les créneaux, les raccourcis par Grimaud et les accès par la route des plages. Amani Limousines vous y conduit depuis Nice, l'aéroport de La Môle ou votre yacht, en Mercedes, au tarif fixe.",
  },
  'chauffeur-russophone': {
    meta_title: 'Chauffeur Russophone Paris — Chauffeur Privé Parlant Russe | Amani Limousines',
    meta_description: "Chauffeur privé parlant russe à Paris. Tourisme de luxe, shopping, événements mondains. Communication en russe. Disponible 24h/24.",
    h1: 'Chauffeur privé russophone à Paris',
    intro: "Paris a toujours attiré la clientèle russophone. Shopping sur les Champs-Élysées, expos au Grand Palais, soirées dans les palaces du 8e. Avoir un chauffeur qui parle russe, c'est pouvoir dire exactement où vous voulez aller, demander un détour par la rue de la Paix, ou changer de programme à la dernière minute — sans que ça devienne compliqué. Nos chauffeurs russophones connaissent Paris par coeur et sont dispo jour et nuit.",
  },
  'convoi-delegations': {
    meta_title: 'Convoi de Véhicules Paris — Transport Délégation & Mission Diplomatique | Amani',
    meta_description: "Transport de délégations officielles à Paris. Convois de 2 à 30 véhicules, missions diplomatiques, ambassades. Chauffeurs formés, coordination centralisée, disponible 24h/24.",
    h1: 'Convoi de véhicules et transport de délégation à Paris — coordination sans faille',
    intro: "Certaines missions nécessitent plus d'un véhicule. Une délégation ministérielle, une visite d'État, un summit corporate, un groupe de dirigeants en tournée : dans ces situations, la coordination entre plusieurs voitures est aussi importante que le confort de chacune. Le transport de délégation à Paris d'Amani Limousines repose sur un dispatching centralisé, une communication radio continue entre les chauffeurs et un chef de convoi disponible sur le terrain.",
  },
  'evenements': {
    meta_title: 'Transport Événementiel Paris — Salons, Fashion Week, Compétitions | Amani Limousines',
    meta_description: "Transport VIP pour vos événements à Paris. Fashion Week, Paris Air Show, Roland Garros, Festival de Cannes, Salon Nautic, Maison & Objet. Flotte dédiée, coordination sur site.",
    h1: 'Transport VIP pour vos événements à Paris',
    intro: "Paris est la capitale mondiale des événements de prestige. Fashion Week, Air Show, Roland Garros, Festival de Cannes : chaque grand rendez-vous génère des flux de transport intenses que seules des équipes rodées à ces contraintes spécifiques peuvent absorber. Amani Limousines intervient sur chaque édition avec des flotte dédiées, des coordinateurs sur site et une réservation des véhicules bien en amont.",
  },
  'evenements/festival-de-cannes': {
    meta_title: 'Chauffeur Privé Festival de Cannes — Transport Nice-Cannes VIP | Amani',
    meta_description: "Transport VIP pour le Festival de Cannes. Transferts Nice CDG, accès Croisette, Red Carpet. Chauffeur privé Cannes disponible toute la durée du festival.",
    h1: 'Chauffeur privé Festival de Cannes — Croisette, Red Carpet, yachts',
    intro: "Cannes en mai, c'est deux semaines où la Côte d'Azur concentre plus de personnalités au mètre carré que n'importe quel autre endroit au monde. Le transport y est une affaire de positionnement, de timing et de discrétion. Amani Limousines déploie une équipe dédiée pendant toute la durée du festival pour les transferts Nice–Cannes avec chauffeur privé, les navettes Croisette et les accès réservés aux projections et soirées.",
  },
  'evenements/grand-prix-monaco': {
    meta_title: 'Chauffeur Privé Grand Prix de Monaco — Transport VIP Monaco | Amani Limousines',
    meta_description: "Transport privé pour le Grand Prix de Monaco. Paris–Monaco en berline de prestige ou Sprinter VIP pour les groupes. Accès paddock, tribunes, yachts en Méditerranée.",
    h1: 'Chauffeur privé pour le Grand Prix de Monaco — 940 km depuis Paris',
    intro: "Monaco en mai, c'est 940 km depuis Paris, environ neuf heures de route — ou deux heures d'avion jusqu'à Nice, suivies d'un transfert de 25 km vers la Principauté. La plupart des clients qui font le déplacement pour le Grand Prix mixent les deux : vol jusqu'à Nice, puis chauffeur pour Monaco et les jours autour. D'autres font le trajet complet en voiture quand la taille du groupe ou les bagages le justifient.",
  },
  'evenements/hippodrome-deauville': {
    meta_title: 'Chauffeur Privé Hippodrome de Deauville — Transfert Paris Deauville | Amani Limousines',
    meta_description: "Transport privé pour l'hippodrome de Deauville. Paris–Deauville en 2h30 en Mercedes. Accès loges, tribunes VIP, arrivées en voitures. Chauffeur disponible à la journée.",
    h1: "Chauffeur privé pour l'hippodrome de Deauville — Paris–Deauville en 2h30",
    intro: "Deauville, c'est 200 km depuis Paris, deux heures trente sur l'A13 selon la circulation. L'hippodrome reste le rendez-vous mondain que les Parisiens font encore, en particulier en août pour les Yearling Sales et le Grand Prix de Deauville. On y vient souvent à plusieurs, on repart tard, et la route du retour en nocturne mérite d'avoir un chauffeur.",
  },
  'evenements/paris-air-show': {
    meta_title: 'Chauffeur Privé Paris Air Show — Transport Salon du Bourget | Amani Limousines',
    meta_description: "Transport VIP pour le Salon International de l'Aéronautique du Bourget. Transferts exposants, délégations gouvernementales, accueil FBO. Convois coordonnés.",
    h1: 'Chauffeur privé Paris Air Show — Salon du Bourget, transport officiel',
    intro: "Le Salon International de l'Aéronautique et de l'Espace du Bourget est le plus grand salon aéronautique au monde. Il se tient tous les deux ans en juin, et concentre en une semaine des centaines de délégations officielles, des ministres, des PDG de constructeurs et des acheteurs de compagnies aériennes du monde entier. Le transport Paris Air Show Le Bourget est une logistique à part entière.",
  },
  'evenements/paris-fashion-week': {
    meta_title: 'Chauffeur Privé Paris Fashion Week — Transport Défilés & Showrooms | Amani',
    meta_description: "Transport VIP pour la Paris Fashion Week. Navettes entre les défilés Chanel, Dior, Louis Vuitton. Chauffeur privé Paris disponible 24h/24 pendant la fashion week.",
    h1: 'Chauffeur privé Paris Fashion Week — entre chaque défilé, sans attente',
    intro: "La Fashion Week parisienne concentre en une semaine les adresses les plus disputées de la capitale. Palais Royal, Grand Palais Éphémère, Trocadéro, Marais, 8ème arrondissement : les défilés se déroulent dans des lieux hétéroclites, souvent peu accessibles aux taxis ordinaires. Un chauffeur privé Paris Fashion Week dédié reste à votre disposition entre chaque défilé, stationné à proximité, prêt à vous déposer à l'entrée VIP suivante.",
  },
  'evenements/roland-garros': {
    meta_title: 'Chauffeur Privé Roland Garros Paris — Transport Loges VIP | Amani Limousines',
    meta_description: "Transport VIP pour Roland Garros. Transferts Porte d'Auteuil, accès loges et hospitalités corporate. Chauffeur privé Paris disponible pendant tout le tournoi.",
    h1: 'Chauffeur privé Roland Garros Paris — transferts et hospitalités VIP',
    intro: "Deux semaines, 500 000 spectateurs, des loges corporate parmi les plus convoitées du sport mondial. Roland Garros génère chaque printemps un besoin de transport VIP intense autour de la Porte d'Auteuil. Un chauffeur privé Roland Garros bien positionné fait toute la différence entre une expérience fluide et une heure de queue dans les embouteillages du 16ème.",
  },
  'evenements/salons-professionnels': {
    meta_title: 'Chauffeur Privé Salons Professionnels Paris — Première Vision, MIF, Paris Air Show | Amani Limousines',
    meta_description: "Transport privé pour salons et foires professionnels à Paris. Paris Air Show, Première Vision, Maison et Objet, MIF Expo. Navette hôtel–stand, mise à disposition chauffeur.",
    h1: 'Chauffeur privé pour salons professionnels à Paris',
    intro: "Les grands salons parisiens — Paris Air Show, Première Vision, Maison et Objet, MIF Expo — attirent des acheteurs, des dirigeants et des délégations du monde entier. La plupart descendent dans des hôtels du 8ème ou du 16ème, et passent leurs journées entre plusieurs halls d'exposition. Un chauffeur dédié au salon supprime les trajets en taxi et les attentes aux arrêts.",
  },
  'excursion-privee': {
    meta_title: 'Excursion Privée au Départ de Paris — Versailles, Champagne, Normandie | Amani',
    meta_description: "Excursions privées en voiture avec chauffeur depuis Paris. Versailles, Champagne, Giverny, Normandie, Loire. Journées sur mesure, guide culinaire disponible.",
    h1: 'Excursion privée au départ de Paris — avec chauffeur, à votre rythme',
    intro: "Paris est à deux heures de Versailles, des vignobles champenois, des plages du Débarquement et des châteaux de la Loire. Un chauffeur privé Paris excursion permet de sortir de la capitale sans horaires imposés, sans train à attraper, sans parking à gérer à destination. Vous arrivez reposé, vous repartez quand vous voulez.",
  },
  'garde-du-corps': {
    meta_title: 'Garde du Corps Paris — Protection Rapprochée & Bodyguard Privé | Amani Limousines',
    meta_description: "Garde du corps et protection rapprochée à Paris. Bodyguard privé pour personnalités, dirigeants et événements. Agents formés, discrétion totale, intervention 24h/24.",
    h1: 'Garde du corps et protection rapprochée à Paris — agents formés, discrétion absolue',
    intro: "Un garde du corps à Paris ne se résume pas à une silhouette imposante derrière vous. C'est un professionnel qui évalue les risques en amont, repère les points de vulnérabilité dans chaque lieu que vous fréquentez et adapte le dispositif en temps réel. Amani Limousines met à votre disposition des agents de protection rapprochée expérimentés, capables d'intervenir dans des contextes variés : déplacements professionnels, événements mondains, séjours privés ou missions longue durée.",
  },
  'longue-distance': {
    meta_title: 'Chauffeur Privé Longue Distance depuis Paris — France & Europe | Amani Limousines',
    meta_description: "Transferts longue distance avec chauffeur privé depuis Paris. Paris–Deauville, Paris–Bruxelles, Paris–Lyon, Paris–Cannes. Berlines et vans VIP équipés Wi-Fi.",
    h1: 'Chauffeur privé longue distance depuis Paris — votre bureau roulant',
    intro: "Le train n'arrive pas toujours à destination, l'avion impose des aéroports souvent excentrés. Pour les trajets de 150 à 1 000 km, un chauffeur privé longue distance Paris offre une alternative que ni le TGV ni l'avion ne peuvent concurrencer sur le critère du confort de travail. Wi-Fi, prises 220V, climatisation individuelle, silence : vous travaillez ou vous dormez, le chauffeur gère.",
  },
  'meet-and-greet': {
    meta_title: 'Meet and Greet Paris — Accueil VIP Aéroport CDG & Orly | Amani Limousines',
    meta_description: "Service Meet and Greet à Paris. Accueil avec pancarte nominative, assistance bagages, Fast Track CDG et Orly. Transfert VIP depuis les salles d'arrivée.",
    h1: 'Service Meet and Greet Paris — l\'accueil qui fait la différence',
    intro: "Le service Meet and Greet à Paris comble l'espace entre la sortie de l'avion et l'intérieur du véhicule. Un assistant dédié vous attend en zone d'arrivée — après la douane — avec une pancarte à votre nom, prend en charge vos bagages et vous conduit directement au véhicule sans que vous ayez à chercher votre chauffeur dans une foule de dizaines de pancartes.",
  },
  'mentions-legales': {
    meta_title: 'Mentions Légales — Amani Limousines',
    meta_description: "Mentions légales d'Amani Limousines, service de chauffeur privé de prestige à Paris.",
    h1: 'Mentions légales',
  },
  'mise-a-disposition': {
    meta_title: "Mise à Disposition Chauffeur Privé Paris — À l'Heure, Demi-Journée, Journée | Amani Limousines",
    meta_description: "Louez un chauffeur privé à l'heure à Paris. Demi-journée, journée complète, plusieurs jours. Compteur arrêté pendant les attentes. Berlines Mercedes et vans VIP.",
    h1: "Mise à disposition d'un chauffeur privé à Paris — votre agenda, notre flexibilité",
    intro: "Contrairement au transfert point A–point B, la mise à disposition place un chauffeur privé à Paris à votre service pour toute une durée déterminée. Le véhicule reste à votre disposition entre chaque rendez-vous — garé à proximité, disponible en deux minutes — ce qui transforme une journée de réunions en Île-de-France en quelque chose de beaucoup plus gérable.",
  },
  'notre-flotte': {
    meta_title: 'Flotte de Véhicules de Prestige Paris — Mercedes, Range Rover, Sprinter VIP | Amani',
    meta_description: "Découvrez notre flotte de véhicules de prestige à Paris. Mercedes Classe E, EQS, S, Maybach, V, G, Range Rover Evoque et Sprinter VIP. Plus de 300 véhicules renouvelés chaque année.",
    h1: 'Véhicules de prestige à Paris — plus de 300 unités',
    intro: "Chez Amani Limousines, la flotte est renouvelée chaque année pour garantir que vos passagers voyagent dans des véhicules récents. Pas de modèles vieillissants tolérés sous prétexte qu'ils sont encore en état de marche. Nos véhicules de prestige à Paris ont moins de trois ans en moyenne, et sont entretenus selon les préconisations constructeur à chaque intervention.",
  },
  'plan-du-site': {
    meta_title: 'Plan du site — Amani Limousines | Chauffeur privé Paris',
    meta_description: "Plan du site Amani Limousines. Retrouvez toutes les pages : services, transferts aéroports, destinations, événements et informations.",
    h1: 'Plan du site',
    intro: "Retrouvez l'ensemble des pages du site Amani Limousines.",
  },
  'securite-rapprochee': {
    meta_title: 'Sécurité Rapprochée Paris — Transport Sécurisé & Garde du Corps | Amani Limousines',
    meta_description: "Service de sécurité rapprochée et transport sécurisé à Paris. Escorte pour personnalités, dirigeants et diplomates. Véhicules banalisés, chauffeurs formés.",
    h1: 'Sécurité rapprochée et transport sécurisé à Paris — discrétion avant tout',
    intro: "La sécurité rapprochée dans un contexte urbain comme Paris n'est pas qu'une affaire de véhicules blindés. C'est surtout une question d'anticipation, de discrétion et de choix d'itinéraires. Nos chauffeurs dédiés aux missions de protection rapprochée à Paris sont formés à la conduite de sécurité, à la lecture de l'environnement urbain et aux protocoles de communication avec les équipes de protection.",
  },
  'taxi-moto': {
    meta_title: 'Taxi Moto Paris — Moto Taxi Premium & Rapide | Amani Limousines',
    meta_description: "Taxi moto à Paris : transport rapide en deux-roues pour éviter les embouteillages. Idéal pour aéroports, gares et rendez-vous urgents. Équipement premium, pilotes expérimentés.",
    h1: 'Taxi moto à Paris — le moyen le plus rapide de traverser la capitale',
    intro: "Paris aux heures de pointe, c'est en moyenne 1h10 pour traverser la ville en voiture. En taxi moto, c'est 25 minutes. Nos pilotes vous transportent en toute sécurité sur des motos premium, avec un équipement complet fourni. Le service est pensé pour les professionnels pressés qui ne peuvent pas se permettre d'arriver en retard : transferts aéroport express, enchaînement de rendez-vous, déplacements urgents dans tout Paris et l'Île-de-France.",
  },
  'transfert-aeroport-beauvais': {
    meta_title: 'Transfert Aéroport Beauvais-Tillé Paris — Chauffeur Privé | Amani Limousines',
    meta_description: "Transfert depuis et vers l'aéroport de Beauvais-Tillé (BVA). Navette privée vers Paris, 85 km en Mercedes. Tarif fixe, suivi des vols, disponible 24h/24.",
    h1: 'Transfert aéroport Beauvais-Tillé — navette privée vers Paris en Mercedes',
    intro: "L'aéroport de Beauvais-Tillé est à 85 km au nord de Paris. Les compagnies low-cost — Ryanair en tête — en font un point de départ pour toute l'Île-de-France. Problème : les navettes officielles mettent une heure et demie et ne vont qu'aux portes Maillot ou Persier. Un chauffeur privé depuis Beauvais vous dépose à votre adresse, pas à un arrêt de bus.",
  },
  'transfert-aeroport-cdg': {
    meta_title: 'Chauffeur Privé Aéroport CDG Paris — Transfert Charles de Gaulle | Amani Limousines',
    meta_description: "Réservez votre chauffeur privé à l'aéroport Charles de Gaulle. Prix fixe, suivi de vol, accueil en salle d'arrivée. Berlines Mercedes et vans VIP disponibles 24h/24.",
    h1: 'Chauffeur privé CDG Paris — transfert aéroport sans attente',
    intro: "Chaque année, plus de 67 millions de passagers transitent par Roissy–Charles de Gaulle. Trouver un chauffeur privé à l'aéroport CDG fiable, à l'heure, et qui connaît réellement les terminaux fait toute la différence. Chez Amani Limousines, nous assurons des transferts depuis et vers CDG sept jours sur sept, de nuit comme de jour, sans compteur ni surprise sur la note.",
  },
  'transfert-aeroport-economique': {
    meta_title: 'Transfert Aéroport Paris — Prix Fixe Sans Surprises | Amani Limousines',
    meta_description: "Transfert aéroport Paris CDG, Orly et Beauvais en voiture avec chauffeur. Prix fixe annoncé avant la réservation. Sans compteur, sans supplément heure de pointe.",
    h1: 'Transfert aéroport Paris — prix fixe, sans compteur',
    intro: "Un taxi depuis CDG peut coûter 55 € ou 110 € selon la circulation, l'heure et l'humeur du compteur. Avec un chauffeur Amani, vous avez un prix annoncé avant de monter dans le véhicule, et ce prix ne change pas. CDG, Orly et Beauvais, 24h/24, 7j/7.",
  },
  'transfert-aeroport-orly': {
    meta_title: 'Chauffeur Privé Aéroport Orly Paris — Transfert ORY | Amani Limousines',
    meta_description: "Transfert avec chauffeur privé à l'aéroport d'Orly. Terminaux 1, 2, 3 et 4 couverts. Prix fixe, suivi de vol, accueil personnalisé. Réservation 24h/24.",
    h1: 'Chauffeur privé Orly Paris — 18 km du centre, zéro stress',
    intro: "Orly est l'aéroport le plus proche de Paris intra-muros. Dix-huit kilomètres séparent le terminal 4 de la Place d'Italie — soit 25 à 35 minutes selon la circulation. Pourtant, sans chauffeur privé à l'aéroport Orly, ces vingt minutes peuvent facilement devenir une heure entre la queue taxi, le rechargement de compte Navigo et un Orlyval parfois bondé. Amani Limousines couvre les quatre terminaux d'Orly avec le même niveau de service que Charles de Gaulle.",
  },
  'transfert-cdg-disneyland': {
    meta_title: 'Transfert CDG Disneyland Paris — Chauffeur Privé Marne-la-Vallée | Amani',
    meta_description: "Transfert aéroport CDG vers Disneyland Paris avec chauffeur privé. 45 km, 40 minutes. Familles et groupes bienvenus. Mercedes Classe V disponible. Prix fixe.",
    h1: 'Transfert CDG Disneyland Paris avec chauffeur privé — familles et groupes',
    intro: "Marne-la-Vallée et Disneyland Paris sont à 45 km de Charles de Gaulle — bien plus proche que Paris intra-muros, et en direction opposée. La Navette officielle Disney Express existe, mais avec des bagages de famille, de jeunes enfants et des horaires décalés, un chauffeur privé CDG Disneyland en Classe V (7 passagers) ou en Sprinter (16 passagers) reste la solution la plus confortable.",
  },
  'transfert-cdg-gare-de-lyon': {
    meta_title: 'Chauffeur Privé CDG Gare de Lyon — Transfert Aéroport Paris | Amani Limousines',
    meta_description: "Transfert entre l'aéroport CDG et la Gare de Lyon avec chauffeur privé. 35 km, 45 min. TGV Lyon, Marseille, Cannes. Prix fixe, disponible 24h/24.",
    h1: 'Chauffeur privé CDG Gare de Lyon — TGV Sud, correspondance directe',
    intro: "La Gare de Lyon dessert Lyon, Marseille, Montpellier, Cannes, Nice, Genève et l'Italie. Depuis CDG, elle est à 35 km — traversant Paris du nord au sud-est. Ce trajet est particulièrement utilisé par les voyageurs internationaux qui arrivent à Charles de Gaulle et poursuivent vers le sud de la France ou la Côte d'Azur en TGV. Un chauffeur privé CDG Gare de Lyon rend cette correspondance fiable, même avec des bagages importants.",
  },
  'transfert-cdg-gare-du-nord': {
    meta_title: 'Chauffeur Privé CDG Gare du Nord — Transfert Aéroport Charles de Gaulle | Amani',
    meta_description: "Transfert entre l'aéroport CDG et la Gare du Nord avec chauffeur privé. 28 km, 35 min. Correspondance Eurostar, Thalys, TGV. Prix fixe à partir de 125 €.",
    h1: 'Chauffeur privé CDG Gare du Nord — Eurostar, Thalys, correspondances sans stress',
    intro: "La Gare du Nord est à 28 km de l'aéroport Charles de Gaulle — le trajet le plus court parmi tous les grands nœuds ferroviaires parisiens. En conditions normales, comptez 30 à 40 minutes. Pour les voyageurs qui enchaînent un vol international et un Eurostar vers Londres, un Thalys vers Bruxelles ou Amsterdam, ou un TGV vers Lille, un chauffeur privé CDG Gare du Nord supprime le RER B avec les valises et garantit l'heure de correspondance.",
  },
  'transfert-cdg-hotel-bristol': {
    meta_title: 'Chauffeur Privé CDG Hôtel Le Bristol Paris — Transfert Faubourg Saint-Honoré | Amani',
    meta_description: "Transfert CDG vers l'Hôtel Le Bristol Paris avec chauffeur privé. 30 km, 40–50 min. Mercedes Classe S. Prix fixe tout compris. Suivi de vol, disponible 24h/24.",
    h1: 'Chauffeur privé CDG Hôtel Le Bristol Paris — Rue du Faubourg, 30 km',
    intro: "Le Bristol Paris est au 112, rue du Faubourg Saint-Honoré, dans le 8ème. À 30 km de Charles de Gaulle, ce trajet prend entre 40 et 50 minutes selon la circulation. Le transfert CDG Le Bristol Paris avec chauffeur privé est le standard que la clientèle de ce palace attend : véhicule haut de gamme, chauffeur en tenue, pancarte nominative en zone d'arrivée, bagages pris en charge dès la sortie du tapis roulant.",
  },
  'transfert-cdg-hotel-george-v': {
    meta_title: 'Chauffeur Privé CDG Four Seasons George V — Transfert Aéroport Avenue George V | Amani',
    meta_description: "Transfert CDG vers le Four Seasons Hotel George V avec chauffeur privé. 32 km, 45 min. Mercedes Classe S ou BMW i7. Prix fixe, accueil VIP. Réservation 24h/24.",
    h1: 'Chauffeur privé CDG Four Seasons George V — avenue George V, 32 km',
    intro: "Le Four Seasons Hotel George V est situé au 31, avenue George V, à quelques pas des Champs-Élysées. Depuis Charles de Gaulle, le trajet couvre 32 km. Un chauffeur privé CDG George V Paris en Classe S ou BMW i7 garantit une arrivée en accord avec le niveau du palace — l'entrée principale du George V dispose d'un dépose-minute couvert, à l'abri des regards.",
  },
  'transfert-cdg-hotel-ritz': {
    meta_title: 'Chauffeur Privé CDG Hôtel Ritz Paris — Transfert Aéroport Place Vendôme | Amani',
    meta_description: "Transfert CDG vers l'Hôtel Ritz Paris (Place Vendôme) avec chauffeur privé. 30 km, 40 min. Mercedes Classe S, accueil VIP, bagagiste à bord. Prix fixe 225 €.",
    h1: 'Chauffeur privé CDG Hôtel Ritz Paris — Place Vendôme, 30 km, 40 minutes',
    intro: "Le Ritz Paris est situé au 15, place Vendôme, dans le 1er arrondissement. Depuis l'aéroport Charles de Gaulle, le trajet couvre environ 30 km par l'A1 puis la traversée de Paris jusqu'à la Rue de la Paix. Un chauffeur privé CDG Hôtel Ritz Paris en Mercedes Classe S ou BMW i7 est la seule arrivée cohérente avec le niveau du palace. L'entrée principale de l'hôtel dispose d'un espace dépose-minute réservé aux véhicules de prestige — votre chauffeur le connaît.",
  },
  'transfert-cdg-la-defense': {
    meta_title: 'Transfert CDG La Défense — Chauffeur Privé Aéroport Paris | Amani Limousines',
    meta_description: "Transfert entre CDG et La Défense avec chauffeur privé. 35 km, 40 minutes. Tour Total, KPMG, Société Générale, Areva. Prix fixe, disponible 24h/24.",
    h1: "Transfert CDG La Défense avec chauffeur privé — quartier d'affaires, service corporate",
    intro: "La Défense est le premier quartier d'affaires européen. Total, LVMH, Société Générale, Areva, KPMG, Deloitte : leurs sièges y sont tous. Les cadres et délégations qui arrivent à CDG et rejoignent La Défense constituent l'une de nos clientèles les plus régulières. Un chauffeur privé CDG La Défense évite les correspondances RER B puis ligne 1 avec les bagages de voyage d'affaires.",
  },
  'transfert-cdg-paris': {
    meta_title: 'Transfert CDG Paris Centre — Chauffeur Privé Charles de Gaulle | Amani',
    meta_description: "Transfert entre l'aéroport CDG et Paris centre avec chauffeur privé. 32 km, 45 minutes. Prix fixe à partir de 125 €. Suivi de vol, disponible 24h/24.",
    h1: 'Transfert CDG Paris avec chauffeur privé — 32 km, prix fixe',
    intro: "Le trajet entre l'aéroport Charles de Gaulle et Paris intra-muros est l'un des plus empruntés d'Île-de-France. 32 kilomètres séparent le Terminal 2E de Notre-Dame de Paris. En conditions normales, comptez 40 à 50 minutes. Avec un chauffeur privé CDG Paris Amani, le prix est fixé à l'avance et ne varie pas selon la durée réelle du trajet.",
  },
  'transfert-cdg-versailles': {
    meta_title: 'Transfert CDG Versailles — Chauffeur Privé Charles de Gaulle Versailles | Amani',
    meta_description: "Transfert entre l'aéroport CDG et Versailles avec chauffeur privé. 55 km, 55 minutes. Château de Versailles, Trianon, hôtels. Prix fixe tout compris.",
    h1: 'Transfert CDG Versailles avec chauffeur privé — 55 km, sans changement',
    intro: "Versailles attire chaque année des millions de visiteurs internationaux qui arrivent majoritairement à Charles de Gaulle. En transports en commun, le trajet CDG–Versailles implique au moins deux correspondances et plus d'une heure trente. Avec un chauffeur privé CDG Versailles, vous êtes devant le Château en 55 minutes environ, directement depuis le terminal, sans rupture de charge.",
  },
  'transfert-hotel-luxe-paris': {
    meta_title: 'Transfert Hôtel de Luxe Paris — Chauffeur Palace & Conciergerie | Amani Limousines',
    meta_description: "Transfert chauffeur privé vers les palaces parisiens : Ritz, George V, Plaza Athénée, Bristol, Meurice, Shangri-La, Peninsula, Lutetia. Service conciergerie et accueil aéroport.",
    h1: "Transfert hôtel de luxe à Paris — de l'aéroport à votre palace, sans transition",
    intro: "L'expérience d'un séjour dans un palace parisien commence dès l'aéroport. Un chauffeur qui vous attend avec votre nom, une berline impeccable, un trajet calme jusqu'à la porte de votre hôtel — c'est le premier contact avec le niveau de service que vous attendez. Amani Limousines travaille avec les concierges des plus grands hôtels de Paris pour garantir une arrivée et un départ à la hauteur de l'établissement.",
  },
  'transfert-le-bourget': {
    meta_title: 'Chauffeur Privé Le Bourget — Transfert Aviation Privée | Amani Limousines',
    meta_description: "Chauffeur privé à l'aéroport du Bourget. Accueil FBO, jets privés, délégations officielles. 15 km de Paris. Disponible 24h/24, flotte Mercedes et vans VIP.",
    h1: 'Chauffeur privé Le Bourget Paris — transferts jets et hélicoptères',
    intro: "L'aéroport du Bourget est la principale plateforme d'aviation d'affaires en France, et l'une des plus fréquentées d'Europe. Dassault Falcon, Bombardier Global, Gulfstream G700 : les appareils qui se posent ici transportent des dirigeants, des délégations gouvernementales et des familles qui n'ont pas de marge sur les horaires. Le transfert chauffeur privé Le Bourget doit être à la hauteur de l'appareil.",
  },
  'transfert-orly-paris': {
    meta_title: 'Transfert Orly Paris Centre — Chauffeur Privé Aéroport Orly | Amani Limousines',
    meta_description: "Transfert entre l'aéroport Orly et Paris centre avec chauffeur privé. 18 km, 25–35 min. Prix fixe à partir de 80 €. Tous terminaux couverts, disponible 24h/24.",
    h1: 'Chauffeur privé Orly Paris — 18 km, le trajet aéroport le plus rapide de la capitale',
    intro: "Orly est l'aéroport géographiquement le plus proche du cœur de Paris. 18 kilomètres séparent Orly 4 de la Place d'Italie — une distance que l'on avale en 25 à 35 minutes par l'A6B, hors heures de pointe. Avec un chauffeur privé Orly Paris centre, vous êtes dans votre hôtel ou votre domicile bien avant que vos bagages aient eu le temps de vous peser.",
  },
  'transfert-prive': {
    meta_title: 'Transfert Privé Paris — Prix Fixe Porte à Porte | Amani Limousines',
    meta_description: "Transfert privé à Paris avec chauffeur. Prix fixe garanti, sans compteur. Aéroports, gares, hôtels et adresses personnalisées. Réservation immédiate.",
    h1: 'Transfert privé à Paris — prix fixe garanti, porte à porte',
    intro: "Le transfert privé est la prestation la plus simple d'Amani Limousines : un point de départ, un point d'arrivée, un prix annoncé à l'avance. Pas de compteur, pas de majoration d'embouteillage, pas de surprise au moment de régler. Le montant que vous voyez dans le devis est celui que vous payez, qu'il y ait des travaux sur le périphérique ou non.",
  },

  // ── English pages ──────────────────────────────────────────────────────────

  'en/bordeaux-airport-transfer': {
    meta_title: 'Bordeaux Airport Transfer — Private Chauffeur from Paris | Amani Limousines',
    meta_description: "Private chauffeur from Paris to Bordeaux and Bordeaux-Mérignac airport. Mercedes fleet, fixed price. Paris to Bordeaux in 5h30 or airport pickup on your schedule.",
    h1: 'Private chauffeur Paris–Bordeaux — 580 km, fixed price',
    intro: "Bordeaux-Mérignac (BOD) is 580 km from Paris. By train it's fast, but the TGV drops you at Saint-Jean station, not at your client's office in the Mériadeck district or a winery in the Médoc. A private chauffeur covers door to door. Paris to Bordeaux in approximately 5 hours 30 minutes, depending on traffic at the Orléans junction.",
  },
  'en/cdg-airport-transfer': {
    meta_title: 'Private Driver CDG Airport Paris — Charles de Gaulle Transfer | Amani Limousines',
    meta_description: "Book a private driver at CDG airport Paris. Fixed price, flight tracking, VIP meet & greet. Mercedes S-Class and vans available 24/7. From €125.",
    h1: 'Private driver CDG airport Paris — fixed price, no surprises',
    intro: "Charles de Gaulle handles over 67 million passengers a year. Finding a reliable private chauffeur at CDG Paris who actually knows the terminal layout — and is there when you land — makes all the difference. Amani Limousines covers all CDG terminals seven days a week, around the clock, at a price agreed before your flight takes off.",
  },
  'en/chamonix-chauffeur': {
    meta_title: 'Chauffeur to Chamonix — Paris to Chamonix Private Transfer | Amani Limousines',
    meta_description: "Private chauffeur from Paris to Chamonix. 600 km, fixed price. Departure from CDG, Orly or any Paris address. Recent Mercedes, available year-round.",
    h1: 'Chauffeur to Chamonix — from Paris and the airports',
    intro: "Paris to Chamonix is 600 km and about 6 hours by road. There is no direct train. Amani Limousines covers this route year-round from Paris, CDG and Orly in recent Mercedes vehicles, with a fixed price agreed before the booking is confirmed. No meter, no surprises at the end of a long drive.",
  },
  'en/close-protection': {
    meta_title: 'Close Protection Paris — Secure Transport & Bodyguard Driver | Amani Limousines',
    meta_description: "Close protection and secure transport in Paris. Discreet vehicles, security-trained drivers, principal and follow cars. Available for VIPs, executives and diplomats.",
    h1: 'Close protection and secure transport in Paris — discretion above all',
    intro: "Urban close protection in Paris is primarily about anticipation, route selection and discretion. Our drivers assigned to secure transport missions in Paris are trained in defensive driving, urban threat awareness and communication protocols with protection teams. They know the alternative routes, the rapid egress points and the access roads that most drivers never use.",
  },
  'en/contact': {
    meta_title: 'Contact — Amani Limousines | Private Driver Paris 24/7',
    meta_description: "Contact Amani Limousines for your private driver in Paris. Phone, WhatsApp, email. Response within 30 minutes. Available 24/7, 365 days a year.",
    h1: 'Contact our team — private driver Paris 24/7',
    intro: "Our team is available around the clock, every day of the year, for bookings, bespoke quotes and logistics questions. We respond within 30 minutes, including overnight and on public holidays.",
  },
  'en/delegation-transport': {
    meta_title: 'Delegation Transport Paris — Vehicle Convoy & Diplomatic Missions | Amani',
    meta_description: "Vehicle convoy and delegation transport in Paris. 2 to 30 vehicles coordinated, diplomatic missions, embassies. Centralised dispatch, 24/7 availability.",
    h1: 'Delegation transport and vehicle convoy in Paris — coordinated, flawless',
    intro: "A ministerial visit, a state arrival, a corporate summit or a group of executives on a Paris tour: these situations require more than a single vehicle. The delegation transport service in Paris from Amani Limousines is built around centralised dispatch, continuous radio communication between drivers and a field coordinator available on site throughout the mission.",
  },
  'en/economical-airport-transfer': {
    meta_title: 'Economical Airport Transfer Paris — Fixed Price, No Meter | Amani Limousines',
    meta_description: "Airport transfer from Paris CDG, Orly and Beauvais with fixed price. No meter, no peak surcharges. Know your fare before you book. Available 24/7.",
    h1: 'Airport transfer Paris — fixed price, no meter',
    intro: "A Paris taxi from CDG can cost €55 or €110 depending on traffic, time of day and how fast the meter runs. With an Amani driver, you have a price before you get in the car, and that price does not change. CDG, Orly and Beauvais, 24 hours a day, seven days a week.",
  },
  'en/events': {
    meta_title: 'VIP Event Transport Paris — Fashion Week, Air Show, Roland Garros | Amani',
    meta_description: "VIP transport for Paris events. Fashion Week, Paris Air Show, Roland Garros, Cannes Film Festival, trade shows. Dedicated fleet, on-site coordinator.",
    h1: 'VIP transport for your events in Paris',
    intro: "Paris hosts the world's most prestigious events. Fashion Week, Air Show, Roland Garros, Cannes Film Festival — each generates intense transport demand that only teams experienced with those specific constraints can absorb. Amani Limousines deploys for every major edition with dedicated fleets, on-site coordinators and vehicles reserved well in advance.",
  },
  'en/haute-savoie-chauffeur': {
    meta_title: 'Haute-Savoie Chauffeur — Paris to Chamonix, Megève, Annecy | Amani Limousines',
    meta_description: "Private chauffeur from Paris to all of Haute-Savoie: Chamonix, Megève, Annecy, Thonon, Évian. Fixed price. From CDG, Orly or any Paris address.",
    h1: 'Haute-Savoie chauffeur — Chamonix, Megève, Annecy and beyond',
    intro: "Haute-Savoie includes destinations that the train serves poorly: Chamonix, Megève, Morzine, the French shore of Lake Geneva. Amani Limousines covers the whole department from Paris, CDG and Orly in recent Mercedes, with a fixed price. The drive is between 5 and 7 hours depending on the destination, with no connections or local shuttles to coordinate on arrival.",
  },
  'en/hourly-hire': {
    meta_title: 'Hourly Hire Private Driver Paris — Chauffeur by the Hour | Amani Limousines',
    meta_description: "Hire a private driver in Paris by the hour. Half-day, full day or multi-day. Vehicle waits during meetings — no meter running. Mercedes fleet, 24/7 availability.",
    h1: 'Private driver Paris by the hour — your schedule, our flexibility',
    intro: "Hourly hire places a private chauffeur in Paris at your service for a set duration. The vehicle stays nearby between each stop — parked, reachable in two minutes — turning a full day of meetings across the city into something considerably more manageable than chasing taxis between appointments.",
  },
  'en/long-distance': {
    meta_title: 'Long Distance Private Driver from Paris — France & Europe | Amani Limousines',
    meta_description: "Long distance chauffeur service from Paris. Paris–Deauville, Paris–Brussels, Paris–Lyon, Paris–Monaco. Wi-Fi equipped Mercedes and VIP vans. Fixed price.",
    h1: 'Long distance private driver from Paris — your rolling office',
    intro: "The train doesn't always reach your destination. The plane forces airports that are often far from where you actually need to be. For journeys between 150 and 1,000 km, a long distance private chauffeur from Paris offers something neither the TGV nor an aircraft can match: a working environment where you control the schedule, the stops and the pace. Wi-Fi, 220V sockets, individual air conditioning, silence.",
  },
  'en/lyon-airport-transfer': {
    meta_title: 'Lyon Airport Transfer — Private Driver from Paris | Amani Limousines',
    meta_description: "Private driver Paris to Lyon and Lyon-Saint Exupéry airport. Mercedes fleet, fixed rates. Paris–Lyon in 4h30 or Lyon airport pickup.",
    h1: 'Private chauffeur Paris–Lyon — 465 km, door to door',
    intro: "Lyon-Saint Exupéry (LYS) is served by direct flights from London, Amsterdam, Frankfurt and elsewhere in Europe. The airport is 25 km east of the city center — not exactly walking distance. A private transfer from Paris covers the full journey or just the airport leg. The A6 motorway is direct, and traffic around Lyon is predictable.",
  },
  'en/marseille-airport-transfer': {
    meta_title: 'Marseille Airport Transfer — Private Chauffeur from Paris | Amani Limousines',
    meta_description: "Private chauffeur Paris to Marseille and Marseille-Provence airport. 780 km, fixed rate. Cannes, Nice and the Côte d'Azur also covered.",
    h1: 'Private chauffeur Paris–Marseille — 780 km along the A6 and A7',
    intro: "Marseille-Provence (MRS) serves the whole western Mediterranean coast. It's also 780 km from Paris — close to 8 hours by road, which makes it a full working day in the car. Most clients who make this journey have a reason: a superyacht, a real estate deal, or a property in the hills above Cassis. The drive is manageable in a single stretch, or you can break it in Lyon (halfway).",
  },
  'en/meet-and-greet': {
    meta_title: 'Meet and Greet Service Paris — VIP Airport Welcome CDG & Orly | Amani',
    meta_description: "Meet and greet service at Paris airports. Name board welcome in arrivals, baggage assistance, Fast Track option at CDG and Orly. Available 24/7.",
    h1: 'Meet and greet Paris airports — from the gate to the car, seamlessly',
    intro: "The meet and greet service in Paris fills the gap between stepping off the aircraft and settling into the vehicle. A dedicated assistant meets your passenger in the arrivals zone — after passport control — with a name board, takes charge of luggage, and guides them directly to the waiting Mercedes without having to scan a crowd of signs or navigate unfamiliar terminal corridors.",
  },
  'en/megeve-chauffeur': {
    meta_title: 'Chauffeur to Megève — Paris to Megève Private Transfer | Amani Limousines',
    meta_description: "Private chauffeur from Paris to Megève. 640 km, fixed price. Departures from CDG, Orly or any address. Mercedes vehicles, 7 days a week, year-round.",
    h1: 'Chauffeur to Megève — from Paris and the airports',
    intro: "Megève has no direct train link from Paris. The closest station is Sallanches, 12 km from the resort, with a change at Geneva or Annecy. For a group with ski bags, a private car from Paris is often faster and always more direct. Amani Limousines covers this route year-round with a fixed price confirmed before departure.",
  },
  'en/orly-airport-transfer': {
    meta_title: 'Private Driver Orly Airport Paris — ORY Transfer | Amani Limousines',
    meta_description: "Private chauffeur at Orly airport Paris. Terminals 1–4 covered. Fixed price from €80, flight tracking, 24/7 availability. Closest airport to Paris centre.",
    h1: "Private driver Orly airport Paris — 18 km from the centre, the shortest airport run",
    intro: "Orly sits just 18 kilometres south of central Paris — closer than CDG by a long margin. In normal traffic, the drive from Orly 4 to the Place d'Italie takes 25 to 30 minutes. A private chauffeur at Orly airport skips the OrlyVal tram, the RER B connection and the stairs — you go straight from the arrivals hall to your Mercedes.",
  },
  'en/our-fleet': {
    meta_title: 'Our Fleet — Prestige Vehicles Paris | Mercedes, Range Rover, Sprinter VIP | Amani',
    meta_description: "Discover Amani Limousines' fleet of prestige vehicles in Paris. Mercedes E-Class, EQS, S-Class, Maybach, V-Class, G-Class, Range Rover Evoque and Sprinter VIP. 300+ vehicles, renewed annually.",
    h1: 'Prestige vehicles in Paris — over 300 units',
    intro: "At Amani Limousines, the fleet is renewed annually to guarantee that passengers travel in recent vehicles. No ageing models kept because they still run. Our prestige vehicles in Paris average under three years old and are maintained to manufacturer specifications at every service interval.",
  },
  'en/private-chauffeur-bordeaux': {
    meta_title: 'Private Chauffeur Bordeaux — Paris to Bordeaux Transfer | Amani Limousines',
    meta_description: "Private chauffeur service Paris to Bordeaux. Driver available in Bordeaux for business and leisure. Fixed price, Mercedes fleet.",
    h1: 'Private chauffeur Paris–Bordeaux — and Bordeaux area',
    intro: "Bordeaux sits 580 km southwest of Paris on the A10. By TGV it is two hours, but the train leaves you at Saint-Jean station, not at the Château Pichon Baron or the conference centre at Bordeaux Lac. A private driver covers the last mile — and the first one. The journey itself takes around 5 hours 30 minutes by road, which for some clients is enough time to work through a set of documents or a few calls without the constraints of a train carriage.",
  },
  'en/private-chauffeur-paris': {
    meta_title: 'Private Chauffeur Paris — 24/7 Mercedes Fleet | Amani Limousines',
    meta_description: "Private chauffeur service in Paris for airport transfers, hourly hire and long distance. Mercedes E, S and V Class. Fixed rates, flight tracking included.",
    h1: 'Private chauffeur in Paris — available 24 hours a day',
    intro: "Paris traffic is not the same at 8am and 10am. The difference can be an hour. A private chauffeur in Paris who knows the city plans around that — not around an app's optimistic estimate. Amani Limousines has been operating in Paris and the Île-de-France region since 2012: airports, business districts, hotels, private addresses. Fixed prices, Mercedes fleet, available seven days a week.",
  },
  'en/private-excursion': {
    meta_title: 'Private Excursion from Paris — Versailles, Champagne, Normandy | Amani Limousines',
    meta_description: "Private day trips from Paris with a chauffeur. Versailles, Champagne, Normandy, Loire Valley, Giverny. Fully tailored itineraries, culinary guide available.",
    h1: 'Private excursion from Paris — with a chauffeur, at your pace',
    intro: "Paris is two hours from Versailles, the Champagne vineyards and the D-Day beaches. A private chauffeur for a day trip from Paris means no train to catch, no parking to manage at the destination, and no departure time imposed by anyone but yourself. You arrive rested, and you leave when you are ready.",
  },
};
